title: "Petr Vaňhara Laboratory"

description: "Research laboratory at Masaryk University, Faculty of Medicine"

theme: minima

markdown: kramdown

plugins:
  - jekyll-feed

minima:
  nav_pages:
    - publications.md
    - team.md
    - projects.md
    - contact.md
